server:
  port: 8081
  servlet:
    context-path: /simuladorambiental

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simuladorambiental?useSSL=false&serverTimezone=UTC
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: admin
      connection-timeout: 5000
      maximum-pool-size: 5
      pool-name: pool-simuladorambiental
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    br.com.aps.simulador.ambiental: DEBUG